#!/bin/bash

# Load ENV variables from a file
source /root/project_env.sh

if [ "$BACKUP_ENABLED" = true ]
then
  /usr/bin/mysqldump -u $MYSQL_USER -p"$MYSQL_PASSWORD" --single-transaction $MYSQL_DATABASE > /home/passky_`date +\%Y-\%m-\%d`.sql
  /usr/bin/sshpass -p "$BACKUP_PASSWORD" /usr/bin/scp -o "ConnectTimeout 3" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -P $BACKUP_PORT /home/passky_`date +\%Y-\%m-\%d`.sql $BACKUP_USER@$BACKUP_HOST:$BACKUP_LOCATION
  /usr/bin/rm /home/passky_`date +\%Y-\%m-\%d`.sql
fi